<?php // check if module is enabled in our extension's backend configuration ?>
<?php if (Mage::getStoreConfig('richsnippets/general/enabled')) { ?>

    <?php
    /**
     * @var Driv_Richsnippets_Block_Jsonld $this
     */
    $structuredData = $this->getStructuredData();
    ?>

    <script type="application/ld+json">
    <?php echo $this->jsonEncodePretty($structuredData); ?>
    </script>

    <?php echo $this->getOpenGraphSnippet($structuredData); ?>

<?php } ?>